const Problem1 = require("../string1.js")

console.log("Test Case- 1")
let result = Problem1(["$100.45", "$1,002.22", "-$123"])
console.log(result) 
console.log("Test Case- 2")
result = Problem1(["$100.4A5", "$1,0A02.22", "-$123.."])
console.log(result) 
console.log("Test Case- 3")
result = Problem1(null)
console.log(result) 
console.log("Test Case- 4")
result = Problem1(undefined)
console.log(result) 
console.log("Test Case- 5")
result = Problem1(["$100.45", null , "-$123"])
console.log(result) 
console.log("Test Case- 6")
result = Problem1([undefined, "null", ""])
console.log(result) 